Terminsuche implementiert.
Edu-Cluster/educluster pull request #19
Opened 2022-12-24 14:04 UTC by vladudenis

2022-12-24 14:05 UTC, vladudenis commented
Erst nach EC-47 mergen.

2022-12-25 11:28 UTC, KammererLara requested changes
is da auch die Clustererstellung schon mit drin? hat mich nur gewundert

2022-12-25 11:28 UTC, KammererLara commented on components/Item/ItemList.tsx
> +                  creator={item.creator}
mit item.creator wird der nach momentanem Stand nix finden..müsste item.person?.username sein

2022-12-25 11:28 UTC, KammererLara commented on components/Item/ItemList.tsx
> +                  creator={item.creator}
same here

2022-12-25 11:34 UTC, KammererLara approved these changes

2022-12-25 11:43 UTC, merged